modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Phoenix-WB/StrippableStone/issues"
[[mods]]
displayURL="https://github.com/Phoenix-WB/StrippableStone"
modId="strippablestone"
version="${file.jarVersion}"
displayName="Strippable Stone"
logoFile="cobblestone.png"
credits="Join my server: https://discord.gg/2cjqwVJtXy"
authors="Phoenix_WB"              
description='''
Strip your stones!
'''

[[dependencies.strippablestone]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.strippablestone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"